--Drop script for FLAVORS table 

DROP TABLE S24_S003_T14_FLAVORS CASCADE CONSTRAINTS; 

 

--Drop script for CUSTOMER_FEEDBACK table 

DROP TABLE S24_S003_T14_CUSTOMER_FEEDBACK CASCADE CONSTRAINTS; 

 

--Drop script for CUSTOMER_DATEOFPURCHASE table 

DROP TABLE S24_S003_T14_CUSTOMER_DATEOFPURCHASE CASCADE CONSTRAINTS; 

 

--Drop script for CUSTOMER_MODEOFPAYMENT table 

DROP TABLE S24_S003_T14_CUSTOMER_MODEOFPAYMENT CASCADE CONSTRAINTS; 

 

--Drop script for CUSTOMER_TRANSACTION table 

DROP TABLE S24_S003_T14_CUSTOMER_TRANSACTION CASCADE CONSTRAINTS; 

 

 

--Drop script for CUSTOMER table 

DROP TABLE S24_S003_T14_CUSTOMER CASCADE CONSTRAINTS; 

 

 

--Drop script for COFFEE_WEIGHT table 

DROP TABLE S24_S003_T14_COFFEE_WEIGHT CASCADE CONSTRAINTS; 

 

--Drop script for FINAL_COFFEE_COST table 

DROP TABLE S24_S003_T14_FINAL_COFFEE_COST CASCADE CONSTRAINTS; 

 

 

--Drop script for COFFEE_TYPE table 

DROP TABLE S24_S003_T14_COFFEE_TYPE CASCADE CONSTRAINTS; 

 

 

--Drop script for COFFEE_COST table 

DROP TABLE S24_S003_T14_COFFEE_COST CASCADE CONSTRAINTS; 


 

-- --Drop script for EMPLOYEE table 

DROP TABLE S24_S003_T14_EMPLOYEE CASCADE CONSTRAINTS; 

 
--Drop script for DELIVERY_AGENT_EMAIL table 
Drop TABLE S24_S003_T14_DELIVERY_AGENT_EMAIL CASCADE CONSTRAINTS;
 

--Drop script for DELIVERY_AGENT_PHONE table 

DROP TABLE S24_S003_T14_DELIVERY_AGENT_PHONE CASCADE CONSTRAINTS; 

 

-- Drop script for COFFE_SHOP_EMAIL table 
DROP TABLE S24_S003_T14_COFFEE_SHOP_EMAIL CASCADE CONSTRAINTS; 

  

-- Drop script for COFFEE_SHOP_PHONE table 

DROP TABLE S24_S003_T14_COFFEE_SHOP_PHONE CASCADE CONSTRAINTS; 

 

-- Drop script for COFFEE_SUPPLIER_TYPE 

DROP TABLE S24_S003_T14_COFFEE_SUPPLIER_TYPE CASCADE CONSTRAINTS; 

 

-- Drop script for COFFEE_SUPPLIER_ADDRESS 

DROP TABLE S24_S003_T14_COFFEE_SUPPLIER_ADDRESS CASCADE CONSTRAINTS; 

 

-- Drop script for COFFEE_SUPPLIER_EMAIL 

DROP TABLE S24_S003_T14_COFFEE_SUPPLIER_EMAIL CASCADE CONSTRAINTS; 

 

-- Drop script for COFFEE_SUPPLIER_PHONE 

DROP TABLE S24_S003_T14_COFFEE_SUPPLIER_PHONE CASCADE CONSTRAINTS; 

 

-- Drop script for PURCHASE

DROP TABLE S24_S003_T14_PURCHASE CASCADE CONSTRAINTS;

 
--Drop script for COFFEE table 

DROP TABLE S24_S003_T14_COFFEE CASCADE CONSTRAINTS; 
 
--Drop script for DELIVERY_AGENT table 

DROP TABLE S24_S003_T14_DELIVERY_AGENT CASCADE CONSTRAINTS; 

-- Drop script for COFFEE_SHOP table 

DROP TABLE S24_S003_T14_COFFEE_SHOP CASCADE CONSTRAINTS; 
 

-- Drop script for COFFEE_SUPPLIER 

DROP TABLE S24_S003_T14_COFFEE_SUPPLIER CASCADE CONSTRAINTS; 
 
