---Coffee Supplier 
CREATE TABLE S24_S003_T14_COFFEE_SUPPLIER ( 
    SUPPLIER_ID INT NOT NULL, 
    NAME VARCHAR2(45) NOT NULL, 
    QUANTITY INT, 
    DATE_OF_DELIVERY DATE, 
    TRACKINGNO VARCHAR2(20), 
    DELIVERYAGENTID INT, 
    DATE_OF_SUPPLY DATE, 
    STATUS VARCHAR2(50), 
    CONSTRAINT PK_COFFEE_SUPPLIER PRIMARY KEY (SUPPLIER_ID) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SUPPLIER_TYPE ( 
    COFFEE_SUPPLIER_ID INT NOT NULL, 
    TYPE_OF_COFFEE VARCHAR2(50) NOT NULL, 
    CONSTRAINT PK_COFFEE_SUPPLIER_TYPE PRIMARY KEY (COFFEE_SUPPLIER_ID, TYPE_OF_COFFEE) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SUPPLIER_ADDRESS ( 
    SUPPLIER_ID  INT NOT NULL, 
    STREET VARCHAR2(100), 
    STATE VARCHAR2(50), 
    CITY VARCHAR2(50), 
    ZIP VARCHAR2(20), 
    CONSTRAINT PK_COFFEE_SUPPLIER_ADDRESS PRIMARY KEY (SUPPLIER_ID) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SUPPLIER_EMAIL ( 
    SUPPLIER_ID INT NOT NULL, 
    SUPPLIER_EMAIL VARCHAR2(100) NOT NULL, 
    CONSTRAINT PK_COFFEE_SUPPLIER_EMAIL PRIMARY KEY (SUPPLIER_ID, SUPPLIER_EMAIL) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SUPPLIER_PHONE ( 
    SUPPLIER_ID INT NOT NULL, 
    PHONE VARCHAR2(20) NOT NULL, 
    CONSTRAINT PK_COFFEE_SUPPLIER_PHONE PRIMARY KEY (SUPPLIER_ID, PHONE) 
); 
 
 

 ----COFFEE SHOP 

CREATE TABLE S24_S003_T14_COFFEE_SHOP (   
    COFFEE_SHOP_ID INT NOT NULL,  
    NAME VARCHAR2(45) NOT NULL, 
    STREET VARCHAR2(100), 
    STATE VARCHAR2(50), 
    CITY VARCHAR2(50), 
    CONSTRAINT PK_COFFEE_SHOP PRIMARY KEY (COFFEE_SHOP_ID) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SHOP_EMAIL ( 
    COFFEE_SHOP_ID INT NOT NULL, 
    COFFEE_SHOP_EMAIL VARCHAR2(100) NOT NULL, 
    CONSTRAINT PK_COFFEE_SHOP_EMAIL PRIMARY KEY (COFFEE_SHOP_ID, COFFEE_SHOP_EMAIL) 
); 
  
CREATE TABLE S24_S003_T14_COFFEE_SHOP_PHONE ( 
    COFFEE_SHOP_ID INT NOT NULL, 
    CS_PHONE VARCHAR2(20) NOT NULL, 
    CONSTRAINT PK_COFFEE_SHOP_PHONE PRIMARY KEY (COFFEE_SHOP_ID, CS_PHONE) 
); 
 
 

---Delivery Agent  
CREATE TABLE S24_S003_T14_DELIVERY_AGENT ( 
    AGENT_ID INT PRIMARY KEY, 
    NAME VARCHAR(100) NOT NULL, 
    STATE VARCHAR(100) NOT NULL, 
    CITY VARCHAR(100) NOT NULL, 
    ZIP VARCHAR(20) NOT NULL, 
    DATEOFDELIVERY DATE, 
    EXPECTEDDATE DATE, 
    DELIVERYCOST DECIMAL(10, 2), 
    REFUNDAMT DECIMAL(10, 2), 
    STATUS VARCHAR(20), 
    TRACKINGNO VARCHAR(50), 
    COFFEE_SHOP_ID INT, 
    FOREIGN KEY (COFFEE_SHOP_ID) REFERENCES S24_S003_T14_COFFEE_SHOP (COFFEE_SHOP_ID) 
); 
  
CREATE TABLE S24_S003_T14_DELIVERY_AGENT_PHONE ( 
    DAGENT_ID INT NOT NULL, 
    PHONE VARCHAR(15) NOT NULL, 
    PRIMARY KEY (DAGENT_ID, PHONE), 
    FOREIGN KEY (DAGENT_ID) REFERENCES S24_S003_T14_DELIVERY_AGENT (AGENT_ID) 
); 
  

CREATE TABLE S24_S003_T14_DELIVERY_AGENT_EMAIL ( 
    DELIVERYAGENT_ID INT NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL, 
    PRIMARY KEY (DELIVERYAGENT_ID, EMAIL), 
    FOREIGN KEY (DELIVERYAGENT_ID) REFERENCES S24_S003_T14_DELIVERY_AGENT (AGENT_ID) 
);

 
 
----Employee 
 
CREATE TABLE S24_S003_T14_EMPLOYEE (  
EMP_ID INT PRIMARY KEY,  
NAME VARCHAR2(50) NOT NULL,  
GENDER VARCHAR2(10),  
EMP_DOJ DATE,  
PAN VARCHAR2(20),  
EMP_DOB DATE,  
SALARY INT,  
DESIGNATION VARCHAR2(50),  
EMP_EMAIL VARCHAR2(100) UNIQUE,  
STREET VARCHAR2(100),  
STATE VARCHAR2(50),  
ZIP VARCHAR2(20),  
EMPP_PHONE VARCHAR2(15),  
EMP_MGRID INT,  
EMP_CHKINTIME TIMESTAMP,  
EMP_CHKOUTTIME TIMESTAMP,  
CONSTRAINT FK_MGR FOREIGN KEY (EMP_MGRID) REFERENCES S24_S003_T14_EMPLOYEE(EMP_ID) ); 
 
 ----COFFEE 
 
CREATE TABLE S24_S003_T14_COFFEE ( 
    COFFEE_ID INT PRIMARY KEY, 
    NAME VARCHAR2(50) NOT NULL, 
    COFFEE_SUPPLIER_ID INT NOT NULL, 
    PACKAGING VARCHAR2(50), 
    COFFEE_SHOP_ID INT,
    CONSTRAINT FK_SUPPLIER FOREIGN KEY (COFFEE_SUPPLIER_ID) REFERENCES S24_S003_T14_COFFEE_SUPPLIER(SUPPLIER_ID),
    CONSTRAINT FK_COFFEE_SHOP_ID FOREIGN KEY (COFFEE_SHOP_ID) REFERENCES S24_S003_T14_COFFEE_SHOP(COFFEE_SHOP_ID) 
); 
 
 
 
CREATE TABLE S24_S003_T14_COFFEE_COST( 
    COFFEE_ID INT, 
    COST INT, 
    PRIMARY KEY (COFFEE_ID, Cost), 
    CONSTRAINT FK_COFFEE FOREIGN KEY (COFFEE_ID) REFERENCES S24_S003_T14_COFFEE(COFFEE_ID) 
); 
 
 

CREATE TABLE S24_S003_T14_COFFEE_TYPE (  
COFFEE_ID INT,  
TYPE VARCHAR2(50),  
PRIMARY KEY (COFFEE_ID, Type),  
CONSTRAINT FK_COFFEE_TYPE FOREIGN KEY (COFFEE_ID) REFERENCES S24_S003_T14_COFFEE (COFFEE_ID));  
 


CREATE TABLE S24_S003_T14_FINAL_COFFEE_COST(  
COFFEE_ID INT,  
COFFEE_COST INT,  
PRIMARY KEY (COFFEE_ID, COFFEE_COST),  
CONSTRAINT FK_FINAL_COFFEE FOREIGN KEY (COFFEE_ID) REFERENCES S24_S003_T14_COFFEE(COFFEE_ID)); 



CREATE TABLE S24_S003_T14_COFFEE_WEIGHT(  
COFFEE_ID INT,  
Weight INT,  
PRIMARY KEY (COFFEE_ID, Weight),  
CONSTRAINT FK_COFFEE_WEIGHT FOREIGN KEY (COFFEE_ID) REFERENCES S24_S003_T14_COFFEE(COFFEE_ID)); 

----Customer 
CREATE TABLE S24_S003_T14_CUSTOMER ( 
    CUST_ID INT NOT NULL, 
    NAME VARCHAR2(100) NOT NULL, 
    PHONE VARCHAR2(20), 
    CITY VARCHAR2(50), 
    STATE VARCHAR2(50), 
    ZIP VARCHAR2(20), 
    MAIL VARCHAR2(100), 
    DOB DATE, 
    GENDER VARCHAR2(10),
    PREFERRED_FLAVOR VARCHAR2(50),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID) 
); 


  
CREATE TABLE S24_S003_T14_CUSTOMER_TRANSACTION ( 
    CUSTOMER_ID INT NOT NULL, 
    COFFEE_SHOP_ID INT NOT NULL, 
    TRANSACTION_D VARCHAR2(50) NOT NULL, 
    CONSTRAINT PK_CUSTOMER_TRANSACTION PRIMARY KEY (CUSTOMER_ID, COFFEE_SHOP_ID, TRANSACTION_D) 
); 
  

CREATE TABLE S24_S003_T14_CUSTOMER_MODEOFPAYMENT ( 
    CUSTOMER_ID INT NOT NULL, 
    COFFEE_SHOP_ID INT NOT NULL, 
    MODE_OF_PAYMENT VARCHAR2(50) NOT NULL, 
    CONSTRAINT PK_CUSTOMER_MODEOFPAYMENT PRIMARY KEY (CUSTOMER_ID, COFFEE_SHOP_ID, MODE_OF_PAYMENT) 
); 
  

CREATE TABLE S24_S003_T14_CUSTOMER_DATEOFPURCHASE ( 
    CUSTOMER_ID INT NOT NULL, 
    COFFEE_SHOP_ID INT NOT NULL, 
    DATE_OF_PURCHASE DATE NOT NULL, 
    CONSTRAINT PK_CUSTOMER_DATEOFPURCHASE PRIMARY KEY (CUSTOMER_ID, COFFEE_SHOP_ID, DATE_OF_PURCHASE) 
); 
 

CREATE TABLE S24_S003_T14_CUSTOMER_FEEDBACK ( 
    CUSTOMER_ID INT NOT NULL, 
    COFFEE_SHOP_ID INT NOT NULL, 
    FEEDBACK VARCHAR2(255), 
    CONSTRAINT PK_CUSTOMER_FEEDBACK PRIMARY KEY (CUSTOMER_ID, COFFEE_SHOP_ID, FEEDBACK) 
); 
 
--FLAVORS TABLE 
 
CREATE TABLE S24_S003_T14_FLAVORS ( 
    FID INT NOT NULL, 
    NAME VARCHAR2(100) NOT NULL, 
    FLAV_SUPPLIER_ID INT, 
    CONSTRAINT PK_Flavors PRIMARY KEY (FID), 
    FOREIGN KEY (FLAV_SUPPLIER_ID) REFERENCES S24_S003_T14_COFFEE_SUPPLIER(SUPPLIER_ID) 
); 
 
--Purchase TABLE

CREATE TABLE S24_S003_T14_PURCHASE (
    CUST_ID INT,
    COFFEE_SHOP_ID INT,
    COFFEE_ID INT,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (CUST_ID, COFFEE_SHOP_ID),
    FOREIGN KEY (COFFEE_ID) REFERENCES S24_S003_T14_COFFEE(COFFEE_ID) 
);


